### PR TITLE
don't allow to use the shell from subprocess

### PR DESCRIPTION
**Pull request by donno2048**

### CODE REVIEW

**Comment by donno2048** [comment]
Oops, deleted the last line

**Comment by iam-py-test** [comment]
@donno2048 thanks!

**Comment by donno2048** [comment]
Wait while I'm updating the tests...

**Comment by donno2048** [comment]
> Wait while I'm updating the tests...

LOL

**Comment by iam-py-test** [comment]
Whoops!
Did not see your comment.
Sorry

**Comment by donno2048** [comment]
It's fine

**Comment by iam-py-test** [comment]
I can give you write access so you don't need PRs

**Comment by donno2048** [comment]
> I can give you write access so you don't need PRs

Please do...

Oh, you did, thanks

**Comment by iam-py-test** [comment]
https://github.com/Random-Security-Tech-For-Users/python-sandbox/invitations
Sorry for my errors; I am used to working on projects alone

**Comment by donno2048** [comment]
> Sorry for my errors; I am used to working on projects alone

No problem...

**Pull request merged**
